export const candidateData = [
  { id: 1, name: "Abiodun Oluwaloseyitan Fiyin", result: "Above Cutoff" },
  { id: 2, name: "Adeloye Esther Adebimpe", result: "Above Cutoff" },
  { id: 3, name: "Emmanuel Osawome Osula", result: "Above Cutoff" },
  { id: 4, name: "Peter Omokefue Audu", result: "Above Cutoff" },
  { id: 5, name: "Ogboji Paul Oche", result: "Above Cutoff" },
  { id: 6, name: "Samson Kayode Ajibade", result: "Above Cutoff" },
  { id: 7, name: "Dolapo Towolawi", result: "Above Cutoff" },
  { id: 8, name: "Abah ojochegbe blessing", result: "Above Cutoff" },
  { id: 9, name: "Oreoluwa Olanrewaju", result: "Above Cutoff" },
  { id: 10, name: "Augustine Uchechukwu Udume", result: "Above Cutoff" },
  { id: 11, name: "Amarachi Chuwa", result: "Above Cutoff" },
  { id: 12, name: "Agbabuokhai Victor", result: "Above Cutoff" },
  { id: 13, name: "ANDREW OSE OKOEKA", result: "Above Cutoff" },
  { id: 14, name: "Idowu Soyebo", result: "Above Cutoff" },
  { id: 15, name: "Muhammad Abubakar Muhammad", result: "Above Cutoff" },
  { id: 16, name: "Mhd-Muktar Onaopepo Olabooye", result: "Above Cutoff" },
  { id: 17, name: "Quwamdeen Omobolaji Durojaiye", result: "Above Cutoff" },
  { id: 18, name: "Oluwadamilola Ameobi", result: "Above Cutoff" },
  { id: 19, name: "Bandikani Rudhra Narasimha", result: "Above Cutoff" },
  { id: 20, name: "Olumilua Divine Favour", result: "Above Cutoff" },
  { id: 21, name: "Jane Okwuchi Onyema", result: "Above Cutoff" },
  { id: 22, name: "Afolabi Babatunde Ajagbe", result: "Above Cutoff" },
  { id: 23, name: "Davidson OkpafI", result: "Above Cutoff" },
  { id: 24, name: "Oluwatosin Olukanni", result: "Above Cutoff" },
  { id: 25, name: "ORILOYE TEMITAYO CELESTINA", result: "Above Cutoff" },
  { id: 26, name: "Adedeji Sulaimon Sunday", result: "Above Cutoff" },
  { id: 27, name: "Okungbowa Emmanuel Victor", result: "Above Cutoff" },
  { id: 28, name: "Noran Mensah", result: "Above Cutoff" },
  { id: 29, name: "Kabir Oladiti OWOLABI", result: "Above Cutoff" },
  { id: 30, name: "Emmanuel Adebola Olowonyo", result: "Above Cutoff" },
  { id: 31, name: "Iyanuoluwa Ajayi", result: "Above Cutoff" },
  { id: 32, name: "Qoosim Adedamola ALABI", result: "Above Cutoff" },
  { id: 33, name: "Waliu Olawale Olaifa", result: "Above Cutoff" },
  { id: 34, name: "Sanni Temitope Rashidat", result: "Above Cutoff" },
  { id: 35, name: "Emmanuel Idowu", result: "Above Cutoff" },
  { id: 36, name: "Udoh Erinyanga Favour", result: "Above Cutoff" },
  { id: 37, name: "Mary Aina Akorede", result: "Above Cutoff" },
  { id: 38, name: "Adedayo Samuel Ogboye", result: "Above Cutoff" },
  { id: 39, name: "Esanju samu", result: "Above Cutoff" },
  { id: 40, name: "Henry Samuel Okonkwo", result: "Above Cutoff" },
  { id: 41, name: "Ojetayo Rahmat Adenike", result: "Above Cutoff" },
  { id: 42, name: "Abubakar Mohammed Ndakomadu", result: "Above Cutoff" },
  { id: 43, name: "Robiu Olayinka Aliu", result: "Above Cutoff" },
  { id: 44, name: "Oluwadamilare Alonge", result: "Above Cutoff" },
  { id: 45, name: "Jalaluddeen, Aminu Abdullahi", result: "Above Cutoff" },
  { id: 46, name: "Maureen Chiedozie", result: "Above Cutoff" },
  { id: 47, name: "Okoye, Ikechukwu Ruben", result: "Above Cutoff" },
  { id: 48, name: "Abdulrasheed Alawode", result: "Above Cutoff" },
  { id: 49, name: "Oluwatosin Agboola Awoniyi", result: "Above Cutoff" },
  { id: 50, name: "Faith Ibunde", result: "Above Cutoff" },
  { id: 51, name: "Ahmed Olayinka Omotosho", result: "Above Cutoff" },
  { id: 52, name: "Mustapha Lawal", result: "Above Cutoff" },
  { id: 53, name: "Oluwatobi Aderemi", result: "Above Cutoff" },
  { id: 54, name: "Rahamat Muktar", result: "Above Cutoff" },
  { id: 55, name: "Ekpo Victor", result: "Above Cutoff" },
  { id: 56, name: "Yusuf Blessing Latifat", result: "Above Cutoff" },
  { id: 57, name: "Chisom Esther Unachukwu", result: "Above Cutoff" },
  { id: 58, name: "Bolutife Adeniji", result: "Above Cutoff" },
  { id: 59, name: "Ogbeifun Enoch Osemare", result: "Above Cutoff" },
  { id: 60, name: "Olakunmi Adefioye Idowu", result: "Above Cutoff" },
  { id: 61, name: "Oluwanifemi Temitope Alabi", result: "Above Cutoff" },
  { id: 62, name: "QUWAM SHONDE OPEYEMI", result: "Above Cutoff" },
  { id: 63, name: "Audu Sanusi Mohammed", result: "Above Cutoff" },
  { id: 64, name: "Elekwa Ezekiel Chisom", result: "Above Cutoff" },
  { id: 65, name: "Omale Godwin", result: "Above Cutoff" },
  { id: 66, name: "Hadiza Bakari", result: "Above Cutoff" },
  { id: 67, name: "IBRAHIM SODIQ", result: "Above Cutoff" },
  { id: 68, name: "Okoh Raymond", result: "Above Cutoff" },
  { id: 69, name: "TRACEY ODION ASHIUMAN", result: "Above Cutoff" },
  { id: 70, name: "ANYEBE Joseph Gabriel", result: "Above Cutoff" },
  { id: 71, name: "Emeka Obasi", result: "Above Cutoff" },
  { id: 72, name: "Olaoye Muhiz", result: "Above Cutoff" },
  { id: 73, name: "Mosopefoluwa Ige", result: "Above Cutoff" },
  { id: 74, name: "Afees Mustapha", result: "Above Cutoff" },
  { id: 75, name: "Samira Asuquo Nyong", result: "Above Cutoff" },
  { id: 76, name: "Vivienne Chidera Ozoekwe", result: "Above Cutoff" },
  { id: 77, name: "ABAH CHEKWUBE DAVID", result: "Above Cutoff" },
  { id: 78, name: "Benson Ememirura Faith", result: "Above Cutoff" },
  { id: 79, name: "Okeke Chineme Regina", result: "Above Cutoff" },
  { id: 80, name: "Oyinlola Adegoke", result: "Above Cutoff" },
  { id: 81, name: "Temitope Majaro", result: "Above Cutoff" },
  { id: 82, name: "Coker Richard Ayodeji", result: "Above Cutoff" },
  { id: 83, name: "Prudence Onyemekara", result: "Above Cutoff" },
  { id: 84, name: "Ifeanyichukwu Ibude", result: "Above Cutoff" },
  { id: 85, name: "Ebijuoworih Douiye", result: "Above Cutoff" },
  { id: 86, name: "FAGBUARO OYINFOLAHAN KOLAWOLE", result: "Above Cutoff" },
  { id: 87, name: "OLUEBUBE CHUKWUNWEKENEAZUBUIKE", result: "Above Cutoff" },
  { id: 88, name: "Odior Aboshioke Faithful", result: "Above Cutoff" },
  { id: 89, name: "Adedayo Adebiyi", result: "Above Cutoff" },
  { id: 90, name: "Bright Ayozie Ugochukwu", result: "Above Cutoff" },
  { id: 91, name: "Tanadeba Leesi", result: "Above Cutoff" },
  { id: 92, name: "Samson Abobarin", result: "Above Cutoff" },
  { id: 93, name: "Anokantsebi Faith Alero", result: "Above Cutoff" },
  { id: 94, name: "Ayomide Daramola Emmanuel", result: "Above Cutoff" },
  { id: 95, name: "Kafayat Sadiku", result: "Above Cutoff" },
  { id: 96, name: "Deborah Oluwatomilola Olunubi", result: "Above Cutoff" },
  { id: 97, name: "Oluwatomilola Deborah Adedeji", result: "Above Cutoff" },
  { id: 98, name: "Ikenna Ifeanyi", result: "Above Cutoff" },
  { id: 99, name: "Ogunbileje joshua", result: "Above Cutoff" },
  { id: 100, name: "Adeagbo Emmanuel", result: "Above Cutoff" },
  { id: 101, name: "Abdulafeez Olaitan", result: "Above Cutoff" },
  { id: 102, name: "FAITH ADAMU KWAHA", result: "Above Cutoff" },
  { id: 103, name: "Mfonido-Abasi Emmanuel Inyangudoh", result: "Above Cutoff" },
  { id: 104, name: "Obasuyi Kemisola Adesola", result: "Above Cutoff" },
  { id: 105, name: "Sina Festus Oluwamojo", result: "Above Cutoff" },
  { id: 106, name: "SULEIMAN YAKUBU AHMED", result: "Above Cutoff" },
  { id: 107, name: "Omoifoh Enahoro Justice", result: "Above Cutoff" },
  { id: 108, name: "Bello Adekunle Obafemi", result: "Above Cutoff" },
  { id: 109, name: "Kenechukwu Michael Chukwu", result: "Above Cutoff" },
  { id: 110, name: "Daniel Oluwatobi Oni", result: "Above Cutoff" },
  { id: 111, name: "Abdulafeez Yusuf", result: "Above Cutoff" },
  { id: 112, name: "Daodu Opeyemi Isaac", result: "Above Cutoff" },
  { id: 113, name: "Olasupo Ebenezer Feyipitan", result: "Above Cutoff" },
  { id: 114, name: "JAMES HALLELUYAH DAMILARE", result: "Above Cutoff" },
  { id: 115, name: "Peter Joshua N", result: "Above Cutoff" },
  { id: 116, name: "Oluwaseun Okundalaye", result: "Above Cutoff" },
  { id: 117, name: "Promise Ifeoma Ezeh", result: "Above Cutoff" },
  { id: 118, name: "EMELI FAVOUR IFUNANYA", result: "Above Cutoff" },
  { id: 119, name: "Sunny Gabriel Hart", result: "Above Cutoff" },
  { id: 120, name: "Hezekiah Adeleke", result: "Above Cutoff" },
  { id: 121, name: "Jonah Omonofa Oluwaiye", result: "Above Cutoff" },
  { id: 122, name: "Lukman Ibrahim Muhammad", result: "Above Cutoff" },
  { id: 123, name: "Mariam Giwa", result: "Above Cutoff" },
  { id: 124, name: "OLADIPUPO, Aishat Mojisola", result: "Above Cutoff" },
  { id: 125, name: "Anifowoshe Hakeem", result: "Above Cutoff" },
  { id: 126, name: "Ademola Qudus Abidemi", result: "Above Cutoff" },
  { id: 127, name: "Jesutofunmi Sangobiyi", result: "Above Cutoff" },
  { id: 128, name: "Asmau Abdulkarim", result: "Above Cutoff" },
  { id: 129, name: "Akinladejo, Emmanuel Akinola", result: "Above Cutoff" },
  { id: 130, name: "Deborah Popoola", result: "Above Cutoff" },
  { id: 131, name: "Damilare Blessing Ekundayo", result: "Above Cutoff" },
  { id: 132, name: "Oditah Oluchukwu Michael", result: "Above Cutoff" },
  { id: 133, name: "SOPELU ROTIMI LEKAN", result: "Above Cutoff" },
  { id: 134, name: "Taiwo Grace Adeniyi", result: "Above Cutoff" },
  { id: 135, name: "Lawal Akeem Alabi", result: "Above Cutoff" },
  { id: 136, name: "Onafuwa Temitayo", result: "Above Cutoff" },
  { id: 137, name: "Abigail Akinsulore", result: "Above Cutoff" },
  { id: 138, name: "Bianca Adole", result: "Above Cutoff" },
  { id: 139, name: "Chiamaka Onyemaechi", result: "Above Cutoff" },
  { id: 140, name: "Oyewole Emmanuel Ayodeji", result: "Above Cutoff" },
  { id: 141, name: "Adedeji Laniyan", result: "Below Cutoff" },
  { id: 142, name: "TAIWO ADE-JONES", result: "Below Cutoff" },
  { id: 143, name: "Oghenekume prosper godspower", result: "Below Cutoff" },
  { id: 144, name: "Tiamiyu Tunde", result: "Below Cutoff" },
  { id: 145, name: "Maryann Ibellow", result: "Below Cutoff" },
  { id: 146, name: "Samuel Israel Abiodun", result: "Below Cutoff" },
  { id: 147, name: "Oghenekevwe Orogun", result: "Below Cutoff" },
  { id: 148, name: "Aregbesola Babajide", result: "Below Cutoff" },
  { id: 149, name: "Paul Ayomide Robinson", result: "Below Cutoff" },
  { id: 150, name: "Sunday Arong Arekam", result: "Below Cutoff" },
  { id: 151, name: "Jimoh Adedoja Suliat", result: "Below Cutoff" },
  { id: 152, name: "Ifeoluwa Odugbesan", result: "Below Cutoff" },
  { id: 153, name: "Nwachukwu Chukwukwe", result: "Below Cutoff" },
  { id: 154, name: "Chidiebere Josephat", result: "Below Cutoff" },
  { id: 155, name: "Grace Enyindah", result: "Below Cutoff" },
  { id: 156, name: "Jennifer Matthew", result: "Below Cutoff" },
  { id: 157, name: "Oladimeji Anthonio", result: "Below Cutoff" },
  { id: 158, name: "Imuzeze Racheal Efe", result: "Below Cutoff" },
  { id: 159, name: "Suleiman Abubakar Isa", result: "Below Cutoff" },
  { id: 160, name: "Faith Ajewole", result: "Below Cutoff" },
  { id: 161, name: "Olatunde Boluwatife Ebenezer", result: "Below Cutoff" },
  { id: 162, name: "Olayinka Ayomide Helen", result: "Below Cutoff" },
  { id: 163, name: "Osamudiamen Ehinor Okojie", result: "Below Cutoff" },
  { id: 164, name: "Salako Toluwalayomi Isaac", result: "Below Cutoff" },
  { id: 165, name: "Abdulquddus Shogo", result: "Below Cutoff" },
  { id: 166, name: "Amina Bintu Muhammed", result: "Below Cutoff" },
  { id: 167, name: "Eze Chinecherem Chukwuemeka", result: "Below Cutoff" },
  { id: 168, name: "Olayiwola Basit Olakunle", result: "Below Cutoff" },
  { id: 169, name: "Eshione Blessing Jeremiah", result: "Below Cutoff" },
  { id: 170, name: "Adereti funmilola Rebecca", result: "Below Cutoff" },
  { id: 171, name: "Hammad Awowole Olamilekan", result: "Below Cutoff" },
  { id: 172, name: "Henry Okatta Chimarame", result: "Below Cutoff" },
  { id: 173, name: "QUEENETH ENIKHE JAMES", result: "Below Cutoff" },
  { id: 174, name: "Esan Michael Ayomide", result: "Below Cutoff" },
  { id: 175, name: "Oyetunde Adebowale Moses", result: "Below Cutoff" },
  { id: 176, name: "Daniel Abioye", result: "Below Cutoff" },
  { id: 177, name: "Abolanle Adebambo", result: "Below Cutoff" },
  { id: 178, name: "Adebiyi Adekunle Ayodeji", result: "Below Cutoff" },
  { id: 179, name: "Adeolu Oluwasegun AWOTUNBO", result: "Below Cutoff" },
  { id: 180, name: "Nornubari Banaanyone BARIVOLE", result: "Below Cutoff" },
  { id: 181, name: "Opara Oluchukwu Isioma", result: "Below Cutoff" },
  { id: 182, name: "AYANBOADE TAIWO ADEWALE", result: "Below Cutoff" },
  { id: 183, name: "Donald Goodhead Akpan", result: "Below Cutoff" },
  { id: 184, name: "Godwin Chinedu Nwekwe", result: "Below Cutoff" },
  { id: 185, name: "Gideon Bature", result: "Below Cutoff" },
  { id: 186, name: "Oniare Olamide", result: "Below Cutoff" },
  { id: 187, name: "ADEWOYIN Marvellous Oluwarotimi", result: "Below Cutoff" },
  { id: 188, name: "Gift Ahmed", result: "Below Cutoff" },
  { id: 189, name: "Mgbojikwe Oge Promise", result: "Below Cutoff" },
  { id: 190, name: "sanusi Babajide AbdulRasheed", result: "Below Cutoff" },
  { id: 191, name: "Yusuf usman abubakar", result: "Below Cutoff" },
  { id: 192, name: "Amao Toluwalase Solomon", result: "Below Cutoff" },
  { id: 193, name: "Justin Oseghale", result: "Below Cutoff" },
  { id: 194, name: "Yahaya mohammed usman", result: "Below Cutoff" },
  { id: 195, name: "Oduba Aramide Christianah", result: "Below Cutoff" },
  { id: 196, name: "Jennifer Lawrence", result: "Below Cutoff" },
  { id: 197, name: "Egberomoh Godsgift", result: "Below Cutoff" },
  { id: 198, name: "Oruoka Gift David", result: "Below Cutoff" },
  { id: 199, name: "Abdulazeez Ridwan", result: "Below Cutoff" },
  { id: 200, name: "Aladenola Olubunmi Temiloluwa", result: "Below Cutoff" },
  { id: 201, name: "Olumi Blessing Oluwabunmi", result: "Below Cutoff" },
  { id: 202, name: "Chukwuebuka Ibeh", result: "Below Cutoff" },
  { id: 203, name: "LEBILE OLUWAMBE ISAAC", result: "Below Cutoff" },
  { id: 204, name: "Goodness Temidayo Andrew", result: "Below Cutoff" },
  { id: 205, name: "Balogun Idris Seun", result: "Below Cutoff" },
  { id: 206, name: "Bello Ojochide Joy", result: "Below Cutoff" },
  { id: 207, name: "UGWU CHIZOBA KINGSLEY", result: "Below Cutoff" },
  { id: 208, name: "Israel Rebecca Olamide", result: "Below Cutoff" },
  { id: 209, name: "Olapade Matini Olayinka", result: "Below Cutoff" },
  { id: 210, name: "Olowookere Ayomikun", result: "Below Cutoff" },
  { id: 211, name: "BABATUNDE YUSUF MUSEDIQ", result: "Below Cutoff" },
  { id: 212, name: "Abimbola Williams", result: "Below Cutoff" },
  { id: 213, name: "Kolade Fredrick Opaireke", result: "Below Cutoff" },
  { id: 214, name: "Adeyemi Micheal Ademola", result: "Below Cutoff" },
  { id: 215, name: "Osayame Eghosa Thomas", result: "Below Cutoff" },
  { id: 216, name: "Ummulkhair salman", result: "Below Cutoff" },
  { id: 217, name: "ADEKUNLE ADEFOLARIN O.", result: "Below Cutoff" },
  { id: 218, name: "Okonkwo izuchukwu Divine", result: "Below Cutoff" },
  { id: 219, name: "Adelani Ifeoluwa Rebecca", result: "Below Cutoff" },
  { id: 220, name: "Banjo Oluwatobiloba Elijah", result: "Below Cutoff" },
  { id: 221, name: "ANYAECHE AMANDA KENNEDY", result: "Below Cutoff" },
  { id: 222, name: "Atawodi Marvelous Ojochenemi", result: "Below Cutoff" },
  { id: 223, name: "ABDULKABIR MUKAILA", result: "Below Cutoff" },
  { id: 224, name: "Olabisi Kamalideen Damilola", result: "Below Cutoff" },
  { id: 225, name: "KEHINDE CECILIA OTUNLA", result: "Below Cutoff" },
  { id: 226, name: "Oyindamola Sanusi", result: "Below Cutoff" },
  { id: 227, name: "Samson Orafidodo", result: "Below Cutoff" },
  { id: 228, name: "Afolabi Comfort Foluke", result: "Below Cutoff" },
  { id: 229, name: "Deborah Akataobi", result: "Below Cutoff" },
  { id: 230, name: "Adekunle Mustura Adetomiwa", result: "Below Cutoff" },
  { id: 231, name: "Oluwadamilola Odetunde", result: "Below Cutoff" },
  { id: 232, name: "Okocha Hossana Ifeanyichukwu", result: "Below Cutoff" },
  { id: 233, name: "ABUBAKAR MUHAMMAD DUNGUS", result: "Below Cutoff" },
  { id: 234, name: "Benedicta Okeke", result: "Below Cutoff" },
  { id: 235, name: "Nurudeen Babalola", result: "Below Cutoff" },
  { id: 236, name: "Nathaniel Okoukoni", result: "Below Cutoff" },
  { id: 237, name: "Chizzy Winner Eluwa", result: "Below Cutoff" },
  { id: 238, name: "Okere Ginikachi", result: "Below Cutoff" },
  { id: 239, name: "Oluwadamilola Esther Johnson", result: "Below Cutoff" },
  { id: 240, name: "Tisan Habila Akut", result: "Below Cutoff" },
  { id: 241, name: "OTITI Onesimus Elechi", result: "Below Cutoff" },
  { id: 242, name: "Ayanfeoluwa Oyedemi", result: "Below Cutoff" },
  { id: 243, name: "Chidiebere Alex Chijioke", result: "Below Cutoff" },
  { id: 244, name: "Amenze Osadolor", result: "Below Cutoff" },
  { id: 245, name: "Elizabeth Francis", result: "Below Cutoff" },
  { id: 246, name: "Yinusa Oluwaseyi Micheal", result: "Below Cutoff" },
  { id: 247, name: "Raji Sulaimon", result: "Below Cutoff" },
  { id: 248, name: "Okpala Vivian Chinenye", result: "Below Cutoff" },
  { id: 249, name: "Abdulkareem Sodiq Olayinka", result: "Below Cutoff" },
  { id: 250, name: "Oyedeji Noah Abayomi", result: "Below Cutoff" },
  { id: 251, name: "Abdullahi Mohammed Ahmed", result: "Below Cutoff" },
  { id: 252, name: "Babatunde Micheal", result: "Below Cutoff" },
  { id: 253, name: "Boyiga Boyiliya Nuga", result: "Below Cutoff" },
  { id: 254, name: "Temitope Hannah olawale", result: "Below Cutoff" },
  { id: 255, name: "Wasiu Akorede Oyedele", result: "Below Cutoff" },
  { id: 256, name: "Miracle Esene", result: "Below Cutoff" },
  { id: 257, name: "Ayomide Oyinloye", result: "Below Cutoff" },
  { id: 258, name: "Ogbole Beauty", result: "Below Cutoff" },
  { id: 259, name: "Oluwatobiloba Oladapo-Loto", result: "Below Cutoff" },
  { id: 260, name: "Mcwilliams Olga Mmasi", result: "Below Cutoff" },
  { id: 261, name: "Oluwatayo oluwaseye", result: "Below Cutoff" },
  { id: 262, name: "David Segun-Agoye", result: "Below Cutoff" },
  { id: 263, name: "Faleye Ayotunde Oladimeji", result: "Below Cutoff" },
  { id: 264, name: "Curtis Okeoghene Rudolph", result: "Below Cutoff" },
  { id: 265, name: "Gideon Chima", result: "Below Cutoff" },
  { id: 266, name: "Ibeh Ozioma Salvation", result: "Below Cutoff" },
  { id: 267, name: "Bolaji Lukman Kayode", result: "Below Cutoff" },
  { id: 268, name: "Sholaja Halimat Adejoke", result: "Below Cutoff" },
  { id: 269, name: "Bossua Doose Joy", result: "Below Cutoff" },
  { id: 270, name: "Akinola Iyinoluwa", result: "Below Cutoff" },
  { id: 271, name: "Samuel Sunday Mbang", result: "Below Cutoff" },
  { id: 272, name: "Doris Jachimma chikere", result: "Below Cutoff" },
  { id: 273, name: "SHUAIB ABIODUN OLADIMEJI", result: "Below Cutoff" },
  { id: 274, name: "Ogheneruona Ekure", result: "Below Cutoff" },
  { id: 275, name: "Anastesia Kosisochukwu Okoli", result: "Below Cutoff" },
  { id: 276, name: "Zayyad Abdullahi", result: "Below Cutoff" },
  { id: 277, name: "Godwin Olabimtan", result: "Below Cutoff" },
  { id: 278, name: "Ibrahim Rukayat Motunrayo", result: "Below Cutoff" },
  { id: 279, name: "Adeniyi Adedamola Faith", result: "Below Cutoff" },
  { id: 280, name: "Anyanwu Elias Emenike", result: "Below Cutoff" },
  { id: 281, name: "Ajetunmobi Temiloluwa", result: "Below Cutoff" },
  { id: 282, name: "Umeh FrankJustice", result: "Below Cutoff" },
  { id: 283, name: "Hassan Abeeb Olaoluwa", result: "Below Cutoff" },
  { id: 284, name: "Juwon Phillips Oluwaleye", result: "Below Cutoff" },
  { id: 285, name: "Stanley Ikechukwu David", result: "Below Cutoff" },
  { id: 286, name: "Faith Omodara", result: "Below Cutoff" },
  { id: 287, name: "Opeyemi Bickersteth", result: "Below Cutoff" },
  { id: 288, name: "Zainab Yusuf", result: "Below Cutoff" },
  { id: 289, name: "Austin Chukwu", result: "Below Cutoff" },
  { id: 290, name: "Apata Daniel oluwasegun", result: "Below Cutoff" },
  { id: 291, name: "Israel Abiodun Adegoke", result: "Below Cutoff" },
  { id: 292, name: "WINNIE UKWUNNA", result: "Below Cutoff" },
  { id: 293, name: "Tobiloba Adeoye", result: "Below Cutoff" },
  { id: 294, name: "Oladapo Daniel Abayomi", result: "Below Cutoff" },
  { id: 295, name: "Oladapo Akande", result: "Below Cutoff" },
  { id: 296, name: "Rickey Afiibor", result: "Below Cutoff" },
  { id: 297, name: "Adeosun Matthew Osungbesan", result: "Below Cutoff" },
  { id: 298, name: "Victory Esele", result: "Below Cutoff" },
  { id: 299, name: "Innocent Okechukwu Orji", result: "Below Cutoff" },
  { id: 300, name: "Ushie Godwin Jedy Agba", result: "Below Cutoff" },
  { id: 301, name: "Mukhtar Zanna Ahmed", result: "Below Cutoff" },
  { id: 302, name: "Kelly Oyaluna", result: "Below Cutoff" },
  { id: 303, name: "AJISAFE ZAINAB ADETUTU", result: "Below Cutoff" },
  { id: 304, name: "Adepegba Abeeb Ayomide", result: "Below Cutoff" },
  { id: 305, name: "Odukoya Oluwabukunmi Dorcas", result: "Below Cutoff" },
  { id: 306, name: "Prevail Falade-Samuel", result: "Below Cutoff" },
  { id: 307, name: "Deborah Onakovwen Aluma", result: "Below Cutoff" },
  { id: 308, name: "Oladipo Olaniyonu", result: "Below Cutoff" },
  { id: 309, name: "Agebe Abel Aluma", result: "Below Cutoff" },
  { id: 310, name: "POPOOLA ADESINA BABATUNDE", result: "Below Cutoff" },
  { id: 311, name: "Ukeme Michael Udoh", result: "Below Cutoff" },
  { id: 312, name: "Eze Ugochukwu Anthony", result: "Below Cutoff" },
  { id: 313, name: "Habeeb Abdulrasheed Baba", result: "Below Cutoff" },
  { id: 314, name: "Tamunoibiaye Jason Kienabere-Kalada", result: "Below Cutoff" },
  { id: 315, name: "Naheem Adekitan", result: "Below Cutoff" },
  { id: 316, name: "Isah Habibullah", result: "Below Cutoff" },
  { id: 317, name: "Adejumoke Esther Olaitan", result: "Below Cutoff" },
  { id: 318, name: "Oladimeji Mariam Asake", result: "Below Cutoff" },
  { id: 319, name: "Yazid Ohiare", result: "Below Cutoff" },
  { id: 320, name: "Saidat Olabisi Sholadoye", result: "Below Cutoff" },
  { id: 321, name: "Agboola Alli Olaitan", result: "Below Cutoff" },
  { id: 322, name: "Oseni Sherif Adeniyi", result: "Below Cutoff" },
  { id: 323, name: "Abiodun Adekanye", result: "Below Cutoff" },
  { id: 324, name: "Precious Asemota", result: "Below Cutoff" },
  { id: 325, name: "Okoh Sylvester Onyemaechi", result: "Below Cutoff" },
  { id: 326, name: "CHINAZA BEN AKUEGBONWU", result: "Below Cutoff" },
  { id: 327, name: "Michael kolade Oshinsanlu", result: "Below Cutoff" },
  { id: 328, name: "Yusuf Babayemi", result: "Below Cutoff" },
  { id: 329, name: "Oladipupo Akande", result: "Below Cutoff" },
  { id: 330, name: "Oluwatosin Adesanya", result: "Below Cutoff" },
  { id: 331, name: "TOKUN Mary OLUWATOYESE", result: "Below Cutoff" },
  { id: 332, name: "Titilayo Hannah Akinkuebi", result: "Below Cutoff" },
  { id: 333, name: "Abdullahi Sulaimon Mohammed", result: "Below Cutoff" },
  { id: 334, name: "Comfort Osewe Enahoro", result: "Below Cutoff" },
  { id: 335, name: "Precious Anuoluwapo Alatise", result: "Below Cutoff" },
  { id: 336, name: "Nkanu Emmanuel", result: "Below Cutoff" },
  { id: 337, name: "Oluwatobiloba Adebayo", result: "Below Cutoff" },
  { id: 338, name: "Abisola Esther Fasetire", result: "Below Cutoff" },
  { id: 339, name: "James Chukwuemeka Agada", result: "Below Cutoff" },
  { id: 340, name: "Ottopa Jennifer Oluwatimilehin", result: "Below Cutoff" },
  { id: 341, name: "Chibuike Chime", result: "Below Cutoff" },
  { id: 342, name: "Best Ohah", result: "Below Cutoff" },
  { id: 343, name: "Idisenimi Hephzibah Halliday", result: "Below Cutoff" },
  { id: 344, name: "Victory Izegaegbe", result: "Below Cutoff" },
  { id: 345, name: "Amuleya oluwatobi roland", result: "Below Cutoff" },
  { id: 346, name: "Olamilekan Ojo", result: "Below Cutoff" },
  { id: 347, name: "Temitope Olorunju", result: "Below Cutoff" },
  { id: 348, name: "OLAOYE IBUKUN DEBORAH", result: "Below Cutoff" },
  { id: 349, name: "Macdonald Uwachukwunenye", result: "Below Cutoff" },
  { id: 350, name: "Joseph Ejeh Ogenyi", result: "Below Cutoff" },
  { id: 351, name: "Ayomikun Sanyaolu", result: "Below Cutoff" },
  { id: 352, name: "OLABODE KAOSARA", result: "Below Cutoff" },
  { id: 353, name: "Perfect Uge Ogheneakpobor", result: "Below Cutoff" },
  { id: 354, name: "Faisal Haruna Hussaini", result: "Below Cutoff" },
  { id: 355, name: "Mary-Ann Goodness Echebiri", result: "Below Cutoff" },
  { id: 356, name: "Akinfenwa Adegoke", result: "Below Cutoff" },
  { id: 357, name: "Ayomide Lawal", result: "Below Cutoff" },
  { id: 358, name: "IBORO MAXWELL WILLEY", result: "Below Cutoff" },
  { id: 359, name: "Samuel Jibowu", result: "Below Cutoff" },
  { id: 360, name: "Sunday, John Oluwaseun", result: "Below Cutoff" },
  { id: 361, name: "Chukwuemeka Augustine Udeh", result: "Below Cutoff" },
  { id: 362, name: "Farook Ajose", result: "Below Cutoff" },
  { id: 363, name: "Chike-Chigbue Ogugua Isabel", result: "Below Cutoff" },
  { id: 364, name: "Yusuf Oladele", result: "Below Cutoff" },
  { id: 365, name: "Ahari Oyindamola Opeyemi", result: "Below Cutoff" },
  { id: 366, name: "Sunday Beshel Ashekong", result: "Below Cutoff" },
  { id: 367, name: "Oyekanmi Olayinka Joshua", result: "Below Cutoff" },
  { id: 368, name: "Samuel Adebile", result: "Below Cutoff" },
  { id: 369, name: "Teninla Sharon Babayemi", result: "Below Cutoff" },
  { id: 370, name: "Mukhtar Mukhtar Muhammad", result: "Below Cutoff" },
  { id: 371, name: "Favour Ruobor", result: "Below Cutoff" },
  { id: 372, name: "Oluwafemi Gbadeyan", result: "Below Cutoff" },
  { id: 373, name: "Nwakanma Queen", result: "Below Cutoff" },
  { id: 374, name: "Boluwatife Omobolanle Adesunloye", result: "Below Cutoff" },
  { id: 375, name: "Alimezia Patel Chukwuma", result: "Below Cutoff" },
  { id: 376, name: "Agofure Oghenetega Deborah", result: "Below Cutoff" },
  { id: 377, name: "Mustapha Boluwatife", result: "Below Cutoff" },
  { id: 378, name: "Adekunle Buhari Ishola", result: "Below Cutoff" },
  { id: 379, name: "Ziyad Isah Chado", result: "Below Cutoff" },
  { id: 380, name: "Abba Joy Ofun", result: "Below Cutoff" },
  { id: 381, name: "Mobolaji Iskil", result: "Below Cutoff" },
  { id: 382, name: "Adepitan Oluwasomidotun Elijah", result: "Below Cutoff" },
  { id: 383, name: "Akinlabi Ayopelumi Ruth", result: "Below Cutoff" },
  { id: 384, name: "Mariam Titilope Aina", result: "Below Cutoff" },
  { id: 385, name: "Salma El-Rufai", result: "Below Cutoff" },
  { id: 386, name: "Florence Nwabuzo-George", result: "Below Cutoff" },
  { id: 387, name: "Arowolo Azeezat Titilope", result: "Below Cutoff" },
  { id: 388, name: "Idiongomfon Clement Okon", result: "Below Cutoff" },
  { id: 389, name: "Ojo Emmanuel", result: "Below Cutoff" },
  { id: 390, name: "Ekundayo Toluwalope Odunayo", result: "Below Cutoff" },
  { id: 391, name: "Ayantobo Bisola Opeyemi", result: "Below Cutoff" },
  { id: 392, name: "Deema Chris-Banigo", result: "Below Cutoff" },
  { id: 393, name: "ADEBIYI SEMINIRE DEBORAH", result: "Below Cutoff" },
  { id: 394, name: "Success Agboyinu", result: "Below Cutoff" },
  { id: 395, name: "OBINNA SAMUEL ONWUHA", result: "Below Cutoff" },
  { id: 396, name: "Jamiu G. Ogunjobi", result: "Below Cutoff" },
  { id: 397, name: "Ahuruonye Adaeze Ann", result: "Below Cutoff" },
  { id: 398, name: "Daniel Okolo", result: "Below Cutoff" },
  { id: 399, name: "Ekwere Nsikak Ezekiel", result: "Below Cutoff" },
  { id: 400, name: "Olamide Ogunbona", result: "Below Cutoff" },
  { id: 401, name: "Daramola Jemimah Olajope", result: "Below Cutoff" },
  { id: 402, name: "Akobundu David Chimdindu", result: "Below Cutoff" },
  { id: 403, name: "Agada Elijah Emmanuel", result: "Below Cutoff" },
  { id: 404, name: "Esther Emenim", result: "Below Cutoff" },
]
